language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3.3-5.2-alpha1"
install:
  - pip install --upgrade pip "setuptools>=20.8.1"
  - pip install "py>=1.4.29"
  - pip install .[test]
  - pip install codecov
script: py.test
after_success:
  - codecov
