language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy-5.5.0"
install:
  - pip install --upgrade pip "setuptools>=24.2.0"
  - pip install "py>=1.4.29"
  - pip install .[test]
  - pip install codecov
script: py.test
after_success:
  - codecov
