language: python
dist: trusty
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3.5-5.7.1-beta"
install:
  - pip install --upgrade pip "setuptools>=24.2.0"
  - pip install "py>=1.4.33"
  - pip install .[test]
  - pip install codecov
script: py.test
after_success:
  - codecov
